### ISSUE TITLE
Add "mailto" support for emailing

### ISSUE THREAD

**Issue by cory2067** [weblab-staff/submission-portal#25]
1. Add to students/teams view. Right now, the email button just says `alert("email")` and does nothing
2. Change milestone grading view to show a mailto instead of that feedback form

**Comment by cory2067** [comment]
Need to consider what to do in the `Email` model, and figure out how to indicate (in the admin UI) if feedback has already been given

**Comment by MFarejowicz** [comment]
Do you mean show a mailto instead of the form here?
<img width="403" alt="Screen Shot 2020-01-06 at 6 26 34 PM" src="https://user-images.githubusercontent.com/10686713/71856492-2289f580-30b2-11ea-8190-a52f7604674b.png">
I think the plan is that upon giving feedback, you'd see who did it and what they said in that place like so:
<img width="403" alt="Screen Shot 2020-01-06 at 6 26 34 PM" src="https://user-images.githubusercontent.com/10686713/71856639-94623f00-30b2-11ea-9b3e-3471dd61f8a9.png">

**Comment by cory2067** [comment]
do you mean keeping that form, and then encoding the entire email body in the mailto href?

**Comment by MFarejowicz** [comment]
What do you mean by "mailto href"? Aren't we using some library to do the emailing for us (looks like we have code in `util.js`)? So we just take the text and stick it in the body?

**Comment by cory2067** [comment]
the idea about "mailto" was to totally trash `nodemailer` and replace it with something like this:

`<a href="mailto:meme@mit.edu">send mail</a>`
when you click on this, it just opens gmail in another window with the recipient autofilled

the idea here was to avoid janky nodemailer bugs by using gmail instead, plus formatting emails in the gmail UI is generally nicer

**Comment by MFarejowicz** [comment]
ah gotcha. I agree that using gmail to email would probably be better, and in that case we'd need to discuss what to do Email model/UI. Let's wait till the meeting after class tomorrow to discuss?

**Comment by MFarejowicz** [comment]
Should be working in both students tab and feedback!
